import { useEffect, useRef, useState } from "react";
import { create } from "zustand";
import { parseServerEvent, serializeClientCommand, type AgentPhase, type SessionSnapshot, type WebError, type WebFileEntry, type WebFilePreview, type WebSessionSummary, type WebUsage } from "@pi-web/protocol";
import { reconnectDelay } from "./reconnect.js";
import { endTool, startTool, toggleTool, updateTool, type ToolView } from "./tool-state.js";
import { ChatTimeline, Composer, ContextPopover, FileSidePeek, Sidebar, TopBar, type Attachment, type Row } from "./components/workspace.js";

type ConnectionState = "connecting"|"connected"|"reconnecting"|"error";
type State={socket?:WebSocket;connection:ConnectionState;phase:AgentPhase;snapshot?:SessionSnapshot;sessions:WebSessionSummary[];fileLists:Record<string,WebFileEntry[]>;preview?:WebFilePreview;tools:Record<string,ToolView>;rows:Row[];error?:WebError;set:(value:Partial<State>)=>void;mergeUsage:(usage:WebUsage,context:SessionSnapshot["context"])=>void;append:(id:string,kind:Row["kind"],text:string)=>void};
const useStore=create<State>((set)=>({connection:"connecting",phase:"idle",sessions:[],fileLists:{},tools:{},rows:[],set:(value)=>set(value),mergeUsage:(usage,context)=>set((state)=>state.snapshot?{snapshot:{...state.snapshot,usage:{...state.snapshot.usage,...usage},context:context?{...state.snapshot.context,...context}:state.snapshot.context}}:{}),append:(id,kind,text)=>set((state)=>{const row=state.rows.find((item)=>item.id===id&&item.kind===kind);return{rows:row?state.rows.map((item)=>item===row?{...item,text:item.text+text}:item):[...state.rows,{id,kind,text}]};})}));
const wsUrl=import.meta.env.VITE_PI_WS_URL??"ws://127.0.0.1:3001/ws"; const imageTypes=new Set<Attachment["mimeType"]>(["image/png","image/jpeg","image/webp","image/gif"]); const imageLimit=20*1024*1024;
function messageText(value:unknown){return typeof value==="string"?value:Array.isArray(value)?value.map((item)=>typeof item==="object"&&item?String((item as {text?:unknown}).text??""):"").join(""):"";}
function send(socket:WebSocket|undefined,command:Record<string,unknown>){if(socket?.readyState===WebSocket.OPEN)socket.send(serializeClientCommand({id:crypto.randomUUID(),...command} as Parameters<typeof serializeClientCommand>[0]));}
function Connection(){const set=useStore((state)=>state.set);const append=useStore((state)=>state.append);const merge=useStore((state)=>state.mergeUsage);useEffect(()=>{let stopped=false,attempts=0;let timer:ReturnType<typeof setTimeout>|undefined;const connect=()=>{set({connection:attempts?"reconnecting":"connecting"});const ws=new WebSocket(wsUrl);ws.onopen=()=>{attempts=0;set({socket:ws,connection:"connected",error:undefined});};ws.onmessage=(event)=>{let value:unknown;try{value=JSON.parse(String(event.data));}catch{return;}const parsed=parseServerEvent(value);if(!parsed.success)return;const data=parsed.data;if(data.type==="snapshot")set({snapshot:data.snapshot,phase:data.snapshot.phase,tools:{},rows:data.snapshot.messages.map((message)=>({id:message.id,kind:message.role,text:messageText(message.content)}))});if(data.type==="sessions")set({sessions:data.sessions});if(data.type==="file_list")useStore.setState((state)=>({fileLists:{...state.fileLists,[data.path??""]:data.entries}}));if(data.type==="file_preview")set({preview:data.preview});if(data.type==="agent_status")set({phase:data.phase});if(data.type==="usage")merge(data.usage,data.context);if(data.type==="message_delta")append(data.messageId,"assistant",data.delta);if(data.type==="thinking_delta")append(data.messageId,"thinking",data.delta);if(data.type==="message_end"&&data.message.role==="system")append(data.message.id,"system",messageText(data.message.content));if(data.type==="tool_start"){useStore.setState((state)=>({tools:startTool(state.tools,data.tool)}));append(data.tool.id,"tool","");}if(data.type==="tool_update")useStore.setState((state)=>({tools:updateTool(state.tools,data.toolId,data.delta,data.output)}));if(data.type==="tool_end")useStore.setState((state)=>({tools:endTool(state.tools,data.toolId,data.success,data.output,data.finishedAt)}));if(data.type==="error")set({error:data.error});if(data.type==="command_ack"&&!data.accepted)set({error:data.error});};ws.onclose=()=>{if(stopped)return;const delay=reconnectDelay(attempts++);set({socket:undefined,connection:"reconnecting"});timer=setTimeout(connect,delay);};ws.onerror=()=>set({connection:"error"});};connect();return()=>{stopped=true;if(timer)clearTimeout(timer);useStore.getState().socket?.close();};},[append,merge,set]);return null;}
export function App(){const {socket,connection,phase,snapshot,sessions,fileLists,preview,tools,rows,error,set,append}=useStore();const [draft,setDraft]=useState("");const [attachments,setAttachments]=useState<Attachment[]>([]);const [contextOpen,setContextOpen]=useState(false);const [compactOpen,setCompactOpen]=useState(false);const [instructions,setInstructions]=useState("");const input=useRef<HTMLInputElement>(null);const idle=phase==="idle";const files=Object.values(fileLists).flat().filter((entry)=>entry.kind==="file");const match=draft.match(/@([^\s@]*)$/);const suggestions=match?files.filter((entry)=>entry.path.toLowerCase().includes(match[1].toLowerCase())).slice(0,6):[];const command=(data:Record<string,unknown>)=>send(socket,data);
const addFiles=async(items:FileList|File[])=>{const result:Attachment[]=[];for(const file of Array.from(items)){if(!imageTypes.has(file.type as Attachment["mimeType"])||file.size>imageLimit){set({error:{code:"invalid_image",message:"Images must be PNG, JPEG, WebP, or GIF and no larger than 20 MB.",recoverable:true}});continue;}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",",2)[1]??"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});result.push({name:file.name,mimeType:file.type as Attachment["mimeType"],data,url:URL.createObjectURL(file)});}setAttachments((current)=>[...current,...result]);};
const submit=()=>{if(!socket)return;if(!idle){command({type:"abort"});return;}const text=draft.trim();if(!text&&!attachments.length)return;command({type:"prompt",text:text||"Please analyze the attached image.",...(attachments.length?{images:attachments.map(({mimeType,data})=>({mimeType,data}))}:{})});append(crypto.randomUUID(),"user",text||"[Image attached]");attachments.forEach((item)=>URL.revokeObjectURL(item.url));setAttachments([]);setDraft("");};
return <main className="app-shell" onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();void addFiles(event.dataTransfer.files);}}><Connection/><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple onChange={(event)=>{if(event.target.files)void addFiles(event.target.files);event.target.value="";}}/><section className="desktop-shell"><TopBar snapshot={snapshot} onContext={()=>setContextOpen(!contextOpen)}/><div className="workspace"><Sidebar sessions={sessions} currentId={snapshot?.sessionId} disabled={!idle||connection!=="connected"} lists={fileLists} onCommand={command} onPreview={(path)=>command({type:"read_file",path})}/><section className="conversation"><ChatTimeline rows={rows} tools={tools} onToggle={(id)=>useStore.setState((state)=>({tools:toggleTool(state.tools,id)}))}/><Composer draft={draft} setDraft={setDraft} attachments={attachments} onAttach={()=>input.current?.click()} onPasteImages={(files)=>void addFiles(files)} onRemove={(index)=>setAttachments((all)=>all.filter((_,item)=>item!==index))} onSubmit={submit} idle={idle} connected={connection==="connected"} models={snapshot?.availableModels??[]} model={snapshot?.model} thinking={snapshot?.thinkingLevel} levels={snapshot?.availableThinkingLevels??[]} onModel={(model)=>command({type:"set_model",provider:model.provider,modelId:model.id})} onThinking={(level)=>command({type:"set_thinking_level",level})} suggestions={suggestions} onMention={(path)=>setDraft((value)=>value.replace(/@[^\s@]*$/,`@${path} `))} error={error} onDismiss={()=>set({error:undefined})}/></section><FileSidePeek preview={preview} onClose={()=>set({preview:undefined})}/></div><ContextPopover snapshot={snapshot} idle={idle} open={contextOpen} onClose={()=>setContextOpen(false)} onCompact={()=>{setContextOpen(false);setCompactOpen(true);}}/></section>{compactOpen&&<div className="modal-backdrop"><form className="compact-modal" onSubmit={(event)=>{event.preventDefault();command(instructions.trim()?{type:"compact",instructions:instructions.trim()}:{type:"compact"});setCompactOpen(false);setInstructions("");}}><h2>Compact context</h2><p>Summarize older conversation messages to free context space.</p><label>Additional instructions</label><textarea autoFocus value={instructions} onChange={(event)=>setInstructions(event.target.value)}/><div><button type="button" onClick={()=>setCompactOpen(false)}>Cancel</button><button type="submit">Compact</button></div></form></div>}</main>;}
