import { useEffect, useState } from "react";
import { ChevronDown, ChevronRight, Copy } from "lucide-react";
import type { ToolView } from "./tool-state.js";

function object(value: unknown): Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function text(value: unknown): string { if (typeof value === "string") return value; const item=object(value); return typeof item.content === "string" ? item.content : ""; }
function pathOf(value: unknown): string { const item=object(value); return typeof item.path === "string" ? item.path : typeof item.file_path === "string" ? item.file_path : "—"; }
function Json({ value }: { value: unknown }) { return <pre>{JSON.stringify(value ?? null, null, 2)}</pre>; }
function Read({ tool }: { tool: ToolView }) { const content=text(tool.execution.output) || text(tool.execution.input); const [html,setHtml]=useState(""); useEffect(()=>{let live=true; void import("shiki").then(({ codeToHtml })=>codeToHtml(content,{lang:"text",theme:"github-dark"}).then((value)=>{if(live)setHtml(value)})).catch(()=>setHtml("")); return()=>{live=false};},[content]); return <><button onClick={()=>void navigator.clipboard?.writeText(pathOf(tool.execution.input))}>Copy path</button><code>{pathOf(tool.execution.input)}</code>{html?<div className="tool-code" dangerouslySetInnerHTML={{__html:html}}/>:<pre>{content.split("\n").map((line,index)=>`${String(index+1).padStart(4)}  ${line}`).join("\n")}</pre>}</>; }
function Write({ tool }: { tool: ToolView }) { return <><code>{pathOf(tool.execution.input)}</code><pre>{text(tool.execution.input) || text(tool.execution.output)}</pre></>; }
function Edit({ tool }: { tool: ToolView }) { const diff=text(tool.execution.output) || String(object(tool.execution.input).diff ?? object(tool.execution.input).patch ?? ""); return <pre className="tool-diff">{diff.split("\n").map((line, index) => <span key={index} className={line.startsWith("+") ? "added" : line.startsWith("-") ? "removed" : "context-line"}>{line}{"\n"}</span>)}</pre>; }
function Bash({ tool }: { tool: ToolView }) { const command=String(object(tool.execution.input).command ?? ""); return <><code>$ {command}</code><pre className="tool-bash">{tool.delta || text(tool.execution.output) || "Waiting for output…"}</pre></>; }
function Generic({ tool }: { tool: ToolView }) { return <><Json value={tool.execution.input}/><Json value={tool.execution.output}/>{tool.delta && <pre>{tool.delta}</pre>}</>; }
export function ToolCard({ text: legacy = "", tool, onToggle }: { text?: string; tool?: ToolView; onToggle?: () => void }) {
  const [legacyOpen,setLegacyOpen]=useState(true); const open=tool?tool.open:legacyOpen; const toggle=onToggle ?? (()=>setLegacyOpen((value)=>!value)); const name=(tool?.execution.name ?? "Tool activity").toLowerCase(); const content=tool ? name==="read"?<Read tool={tool}/>:name==="write"?<Write tool={tool}/>:name==="edit"?<Edit tool={tool}/>:name==="bash"?<Bash tool={tool}/>:<Generic tool={tool}/> : <pre>{legacy || "Waiting for output…"}</pre>;
  return <article className="tool-card"><header><button onClick={toggle}>{open?<ChevronDown size={15}/>:<ChevronRight size={15}/>} {tool?.execution.name ?? "Tool activity"}</button><span>{tool?.execution.status}</span><button data-testid="tool-copy" aria-label="Copy tool output" onClick={()=>void navigator.clipboard?.writeText(tool ? `${tool.delta}\n${JSON.stringify(tool.execution.output ?? null)}` : legacy)}><Copy size={14}/></button></header>{open&&<div className="tool-content">{content}</div>}</article>;
}
