import { useEffect, useRef, useState, type ReactNode } from "react";
import { ChevronDown, ChevronRight, Copy, FileText, Folder, ImagePlus, Plus, RefreshCw, Send, Settings, Square, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeSanitize from "rehype-sanitize";
import type { AgentPhase, SessionSnapshot, WebError, WebFileEntry, WebFilePreview, WebModel, WebSessionSummary } from "@pi-web/protocol";
import { ToolCard } from "../tool-card.js";
import type { ToolView } from "../tool-state.js";
import { isAtLatest, scrollToLatest } from "../timeline-scroll.js";

export type Row = { id: string; kind: "user" | "assistant" | "thinking" | "tool" | "system"; text: string };
export type Attachment = { name: string; mimeType: "image/png" | "image/jpeg" | "image/webp" | "image/gif"; data: string; url: string };
export type Command = (command: Record<string, unknown>) => void;

function MarkdownCode({ className, children }: { className?: string; children?: ReactNode }) { const value=String(children ?? "").replace(/\n$/, ""); const [copied,setCopied]=useState(false); const block=Boolean(className); return block ? <span className="markdown-code"><button onClick={() => void navigator.clipboard?.writeText(value).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1200); })}><Copy size={13}/>{copied ? "Copied" : "Copy"}</button><code className={className}>{value}</code></span> : <code>{value}</code>; }
function Message({ row }: { row: Row }) { if (row.kind === "thinking") return <details className="thinking"><summary>› Thinking</summary><pre>{row.text || "…"}</pre></details>; if (row.kind === "assistant") return <article className="message assistant"><span className="message-label">Eureka</span><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]} components={{ code: MarkdownCode }}>{row.text}</ReactMarkdown></div></article>; return <article className={`message ${row.kind}`}><span className="message-label">{row.kind === "user" ? "You" : "System"}</span><pre>{row.text}</pre></article>; }

function Explorer({ lists, onCommand, onPreview }: { lists: Record<string, WebFileEntry[]>; onCommand: Command; onPreview: (path: string) => void }) { const [open,setOpen]=useState<Set<string>>(new Set()); const render=(parent="",depth=0): ReactNode => (lists[parent] ?? []).map((entry) => <div key={entry.path}><button className="tree-row" style={{ paddingLeft: 8+depth*14 }} onClick={() => { if(entry.kind === "directory") { const next=new Set(open); if(next.has(entry.path)) next.delete(entry.path); else { next.add(entry.path); onCommand({type:"list_files",path:entry.path}); } setOpen(next); } else onPreview(entry.path); }}>{entry.kind === "directory" ? open.has(entry.path) ? <ChevronDown/> : <ChevronRight/> : <FileText/>}{entry.kind === "directory" && <Folder/>}<span>{entry.name}</span></button>{entry.kind === "directory" && open.has(entry.path) && render(entry.path,depth+1)}</div>); return <section className="sidebar-section"><div className="sidebar-heading"><span>FILES</span><button aria-label="Refresh files" onClick={() => onCommand({type:"list_files"})}><RefreshCw/></button></div>{render()}</section>; }

export function Sidebar({ sessions, currentId, disabled, lists, onCommand, onPreview }: { sessions: WebSessionSummary[]; currentId?: string; disabled: boolean; lists: Record<string, WebFileEntry[]>; onCommand: Command; onPreview: (path:string)=>void }) { return <aside className="sidebar"><button className="new-chat" disabled={disabled} onClick={() => onCommand({type:"new_session"})}><Plus/>New chat</button><section className="sidebar-section"><div className="sidebar-heading"><span>SESSIONS</span></div>{sessions.map((session) => <button key={session.id} className={`session ${session.id===currentId ? "active" : ""}`} disabled={disabled || session.id===currentId} onClick={() => onCommand({type:"switch_session",sessionId:session.id})}><span>{session.name || session.preview || "New session"}</span><small>{new Date(session.modifiedAt).toLocaleDateString()}</small></button>)}</section><Explorer lists={lists} onCommand={onCommand} onPreview={onPreview}/></aside>; }

export function TopBar({ snapshot, onContext }: { snapshot?: SessionSnapshot; onContext: () => void }) { const project=snapshot?.cwd?.replace(/\\/g,"/").split("/").filter(Boolean).at(-1) ?? "Project"; return <header className="topbar"><b>Eureka</b><span className="crumb">/</span><span>{project}</span><span className="top-spacer"/><button className="context-trigger" onClick={onContext}>{snapshot?.context?.percentage?.toFixed(0) ?? "—"}% context</button><button className="icon-control" title="Settings"><Settings/></button></header>; }

export function ContextPopover({ snapshot, idle, open, onClose, onCompact }: { snapshot?: SessionSnapshot; idle:boolean; open:boolean; onClose:()=>void; onCompact:()=>void }) { if(!open) return null; const context=snapshot?.context; const usage=snapshot?.usage; return <div className="popover context-popover"><button className="popover-close" onClick={onClose}><X/></button><h2>Context</h2><p>{context?.usedTokens?.toLocaleString() ?? "—"} / {context?.maxTokens?.toLocaleString() ?? "—"}</p><div className="meter"><i style={{width:`${context?.percentage ?? 0}%`}}/></div><dl><div><dt>Input</dt><dd>{usage?.inputTokens?.toLocaleString() ?? "—"}</dd></div><div><dt>Output</dt><dd>{usage?.outputTokens?.toLocaleString() ?? "—"}</dd></div><div><dt>Cache</dt><dd>{usage?.cacheReadTokens?.toLocaleString() ?? "—"}</dd></div><div><dt>Cost</dt><dd>{usage?.cost === undefined ? "—" : `$${usage.cost.toFixed(4)}`}</dd></div></dl><button className="secondary-action" disabled={!idle} onClick={onCompact}>Compact context</button></div>; }

export function ChatTimeline({ rows, tools, onToggle }: { rows:Row[]; tools:Record<string,ToolView>; onToggle:(id:string)=>void }) { const [follow,setFollow]=useState(true); const timeline=useRef<HTMLDivElement>(null); useEffect(()=>{if(follow&&timeline.current)scrollToLatest(timeline.current);},[follow,rows,tools]); return <div className="timeline-wrap"><div className="timeline" ref={timeline} onScroll={(event)=>setFollow(isAtLatest(event.currentTarget))}>{rows.length ? rows.map((row) => row.kind === "tool" ? <ToolCard key={`tool-${row.id}`} text={row.text} tool={tools[row.id]} onToggle={()=>onToggle(row.id)}/> : <Message key={`${row.kind}-${row.id}`} row={row}/>) : <div className="empty-chat"><h1>Eureka</h1><h2>What are we building?</h2><p>Ask about your codebase, fix a bug, run tests, or make a change.</p><div><span>Explain this project</span><span>Find potential bugs</span><span>Run the tests</span><span>Review recent changes</span></div></div>}</div>{!follow && rows.length>0 && <button className="jump-latest" onClick={()=>{if(timeline.current)scrollToLatest(timeline.current);setFollow(true);}}>Jump to latest</button>}</div>; }

function Picker({ label, value, items, disabled, onChange }: { label:string; value:string; items:string[]; disabled:boolean; onChange:(value:string)=>void }) { const [open,setOpen]=useState(false); return <div className="picker"><button disabled={disabled} onClick={()=>setOpen(!open)}>{value || label}<ChevronDown/></button>{open && <div className="popover picker-menu"><strong>{label}</strong>{items.map((item)=><button key={item} className={item===value?"selected":""} onClick={()=>{onChange(item);setOpen(false);}}>{item===value?"✓ ":""}{item}</button>)}</div>}</div>; }

export function Composer({ draft, setDraft, attachments, onAttach, onPasteImages, onRemove, onSubmit, idle, connected, models, model, thinking, levels, onModel, onThinking, suggestions, onMention, error, onDismiss }: { draft:string; setDraft:(value:string)=>void; attachments:Attachment[]; onAttach:()=>void; onPasteImages:(files:File[])=>void; onRemove:(index:number)=>void; onSubmit:()=>void; idle:boolean; connected:boolean; models:WebModel[]; model?:WebModel; thinking?:string; levels:string[]; onModel:(model:WebModel)=>void; onThinking:(level:string)=>void; suggestions:WebFileEntry[]; onMention:(path:string)=>void; error?:WebError; onDismiss:()=>void }) {
  const chooseModel=(name:string)=>{const found=models.find((item)=>item.name===name);if(found)onModel(found);};
  return <>
    {error&&<div className="safe-error">{error.message}<button onClick={onDismiss}><X/></button></div>}
    <div className="composer">
      {attachments.map((item,index)=><div className="attachment" key={item.url}><img src={item.url} alt={item.name}/><button onClick={()=>onRemove(index)}><X/></button></div>)}
      <textarea value={draft} onPaste={(event)=>{const files=Array.from(event.clipboardData.files);if(files.length){event.preventDefault();onPasteImages(files);}}} onChange={(event)=>setDraft(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();onSubmit();}}} placeholder="Ask Eureka..."/>
      <div className="composer-footer"><button className="attach" title="Attach images" onClick={onAttach}><ImagePlus/></button><Picker label="Select model" disabled={!idle||!connected} value={model?.name ?? "Select model"} items={models.map((item)=>item.name)} onChange={chooseModel}/><Picker label="Thinking" disabled={!idle||!connected} value={thinking ?? "Thinking"} items={levels} onChange={onThinking}/><span className={`agent-status ${idle?"":"busy"}`}>● {idle?"Ready":"Working"}</span><button className="send" disabled={!connected} onClick={onSubmit}>{idle?<Send/>:<Square/>}</button></div>
      {suggestions.length>0&&<div className="file-suggestions">{suggestions.map((entry)=><button key={entry.path} onMouseDown={(event)=>{event.preventDefault();onMention(entry.path);}}>{entry.path}</button>)}</div>}
    </div>
  </>;
}

export function FileSidePeek({ preview, onClose }: { preview?:WebFilePreview; onClose:()=>void }) { if(!preview)return null; return <aside className="side-peek"><header><strong>{preview.path}</strong><button onClick={onClose}><X/></button></header><button className="copy-path" onClick={()=>void navigator.clipboard?.writeText(preview.path)}>Copy path</button>{preview.kind==="image"?<img src={`data:${preview.mimeType};base64,${preview.data}`} alt={preview.path}/>:preview.kind==="text"?<pre>{preview.content}</pre>:<p>Preview unavailable: {preview.reason.replace("_"," ")}</p>}</aside>; }
