import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("Haze authentication protects Eureka while marketplace access remains permission-scoped", () => {
  const provider = readFileSync("lib/auth/provider.ts", "utf8");
  const start = readFileSync("app/api/marketplace-auth/start/route.ts", "utf8");
  const callback = readFileSync("app/api/marketplace-auth/callback/haze/route.ts", "utf8");
  const session = readFileSync("app/api/marketplace-auth/session/route.ts", "utf8");
  const hazeProvider = readFileSync("lib/auth/haze-oidc.ts", "utf8");
  const authSession = readFileSync("lib/auth/session.ts", "utf8");
  const proxy = readFileSync("proxy.ts", "utf8");
  assert.match(provider, /getIdentityProvider/);
  assert.match(start, /codeChallenge/);
  assert.match(start, /callbackOrigin/);
  assert.match(start, /request\.headers\.get\("host"\)/);
  assert.doesNotMatch(callback, /MARKETPLACE_PERMISSION/);
  assert.match(callback, /response\.cookies/);
  assert.match(callback, /appOrigin/);
  assert.match(session, /response\.cookies/);
  assert.match(session, /safeAvatarUrl/);
  assert.match(hazeProvider, /phone\?: string/);
  assert.match(hazeProvider, /avatar_url/);
  assert.match(hazeProvider, /prompt: "login"/);
  assert.match(hazeProvider, /IdentityProviderError/);
  assert.match(authSession, /persistedSession/);
  assert.match(authSession, /MARKETPLACE_PERMISSION/);
  assert.match(authSession, /avatarUrl: undefined/);
  assert.doesNotMatch(proxy, /WWW-Authenticate/);
  assert.match(proxy, /isOAuthNavigation/);
  assert.match(proxy, /readAuthSessionValue/);
  assert.match(proxy, /Authentication required/);
  assert.match(proxy, /marketplace-auth\/callback\/haze/);
  assert.match(proxy, /marketplace-auth\/start/);
});
